
# READ_DB_ENV: str = "READ_DB_SESSION"
# WRITE_DB_ENV: str = "WRITE_DB_SESSION"
# READ_REPLICA_ENV: str = "READ_REPLICA_ALLOWED"
# DB_SESSION_ENV: str = "DB_SESSION"

READ_REPLICA_ENABLED: bool = False
