on: push
jobs:
  deploy:
    name: Build and deploy package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          node-version: 16.x

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          node-version: 16.x

      - name: Install build dependencies
        run: |
          pip install build
      - name: Build package
        run: |
          python -m build
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_UPLOAD_TOKEN }}
          node-version: 16.x
