run-name: ${{ github.actor }}
on: [ push, pull_request ]

jobs:
  pytest:
    name: Run tests with pytest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.7, 3.8, 3.9, '3.10', '3.11' ]
    steps:
      - name: Setup Test Db
        run: |
          docker pull danielhasan1/mysql_employees_test_db
          docker run -it --name test danielhasan1/mysql_employees_test_db bash
          docker exec -it test bash
          git clone https://github.com/datacharmer/test_db.git
          cd test_db
          mysql -u root -p
          123456
          mysql -t < employees.sql
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install -e .[test]
#      - name: Run linting (flake8)
#        run: |
#          flake8 ./fastapi_listing ./tests
#      - name: Run linting (isort)
#        run: |
#          isort --check-only ./fastapi_listing ./tests
      - name: Run tests
        run: |
          pytest
